# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Caribbean Crisis NYC
tagline:          'A Jekyll theme'
description:      'A one-month jornada of independent discussions & workshops about Puerto Rico and the Caribbean as the region faces odious debt, unnatural disasters, and forced migration.'
url:              "http://caribbeancrisis.github.io"
baseurl:          '/calendario-draft'

author:
  name:           'Alex Gil'
  url:            https://www.elotroalex.com


# Custom vars
version:          2.1.0

github:
  repo:           https://elotroalex.github.com/calendar-draft

gems: [jekyll-paginate]
